# 카카오2017 3차 코테 압축
# https://tech.kakao.com/2017/11/14/kakao-blind-recruitment-round-3/

msg = "THATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITIS"


def solution(msg):
    answer = []
    N = len(msg)
    # 사전 초기화
    dict = [""]
    for i in range(65, 91):
        dict.append(chr(i))
    max_word_length = 1
    idx = 0
    while idx < N:
        for word_length in range(max_word_length, 0, -1):
            selected = msg[idx : idx + word_length]
            if selected in dict:
                answer.append(dict.index(selected))
                dict.append(msg[idx : idx + word_length + 1])
                idx += word_length
                max_word_length = max(
                    max_word_length, word_length + 1
                )  # 사전에 있는 단어의 최대 길이 갱신
                break
    return answer


print(solution(msg))